feature: use code sign

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -11,10 +11,17 @@ jobs:
     
     steps:
     - uses: actions/checkout@v1
+    - uses: apple-actions/import-codesign-certs@v1
+      with: 
+        p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
+        p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
     - name: install depencies
       run: pod install
     - name: archive
-      run: xcodebuild archive -workspace YPaste.xcworkspace -scheme YPaste -archivePath ./archive-YPaste -configuration Release
+      run: |
+      xcodebuild archive -workspace YPaste.xcworkspace -scheme YPaste -archivePath ./archive-YPaste -configuration Release
+      echo "export archive"
+      /usr/bin/xcodebuild -exportArchive -archivePath ./archive-YPaste.xcarchive -exportOptionsPlist "./scripts/ExportOptions.plist" -exportPath ./apps/ || { echo "Export Archive Failed : xcodebuild exportArchive action failed"; exit 1; }
     - name: copy app && zip app && generate appcast
       env:
         sparkle_key: ${{ secrets.sparkle_key }}
